#Post Trade Automation Dashboard ############################################################################################################################################################

# ABOUT: This script takes the simulated trade blotter from generate_trades.py,
# cleans it, runs 6 automated validation/risk checks, calculates operational KPIs,
# calculates value-based exposure measures, works out the average time-to-settlement
# from the real lifecycle timestamps, and generates an AI operational summary using a
# local LLM (Llama 3.2 via Ollama). Everything is exported as CSV and Excel reports
# for app.py to read.

# WHAT THE APP DOES / BUILD STAGES:
# 1 XD. Load data - read the simulated trades + lifecycle events generated by generate_trades.py
# 2 XD. Clean data - standardise text formatting, remove extra spaces, fix capitalisation, parse dates
# 3 XD. Validate data - 6 checks: duplicates, missing owners, missing settlement dates,
#       failed trades, overdue trades, high-priority failed trades
# 4 XD. Calculate KPIs - count-based rates (completion/failure/overdue/high-priority failure)
# 5 XD. Calculate exposure - 4 value-based notional measures (total/outstanding/failed/overdue)
# 6 XD. Calculate average time-to-settlement from the real lifecycle timestamps
# 7 XD. Generate AI operational summary using Llama 3.2
# 8 XD. Export everything as CSV + Excel reports for the Streamlit dashboard to read

#Libraries ############################################################################################################################################################
import os
import pandas as pd
    # nicknames pandas -> pd

# Make sure the output folders exist before anything tries to write into them -
# a fresh clone of the repo won't have them, since git doesn't track empty
# directories
os.makedirs("Reports/CSV", exist_ok=True)
os.makedirs("Reports/Excel", exist_ok=True)

try:
    from ollama import chat
    OLLAMA_AVAILABLE = True
except ImportError:
    OLLAMA_AVAILABLE = False
        # ollama library not installed at all - handled the same way as "server not running"

#Functions ######################################################################################

def print_validation_check(title, dataframe):
    count = len(dataframe)
    print(f"\nNumber of {title}:", count)
    if count > 0:
        print(f"{title}:")
        print(dataframe)


#Load raw data ############################################################################################################################################################
raw_df = pd.read_csv("Data/trades.csv")
lifecycle_df = pd.read_csv("Data/lifecycle_events.csv", parse_dates=["timestamp"])
    #df = dataframe

clean_df = raw_df.copy()

#Clean data - spelling, capitalisation and duplicates ############################################################################################################################################################
clean_df["client_name"] = clean_df["client_name"].str.strip()
clean_df["status"] = clean_df["status"].str.strip().str.title()
clean_df["priority"] = clean_df["priority"].str.strip().str.title()
clean_df["issue_type"] = clean_df["issue_type"].str.strip()
clean_df["owner"] = clean_df["owner"].str.strip()
clean_df["asset_class"] = clean_df["asset_class"].str.strip()
clean_df["product"] = clean_df["product"].str.strip()
clean_df["side"] = clean_df["side"].str.strip().str.title()
    #.str.strip() = removes spaces
    #str.title() = standardises capitalisation, so e.g. "FAILED" == "Failed" -> True instead of False

duplicate_trades = clean_df[clean_df["trade_id"].duplicated()]
number_of_duplicate_trades = len(duplicate_trades)
clean_df = clean_df.drop_duplicates(subset="trade_id")
    #.drop_duplicates, .strip etc are called methods

# Convert dates/times - errors="coerce" turns anything unparseable (including
# already-missing values) into NaT rather than crashing the whole script
clean_df["settlement_date"] = pd.to_datetime(clean_df["settlement_date"], errors="coerce")
clean_df["trade_date"] = pd.to_datetime(clean_df["trade_date"], errors="coerce")

#Inspect data ############################################################################################################################################################
raw_total_trades = len(raw_df)
    #may contain duplicates

print("CSV column names:")
print(clean_df.columns)
print("\nThe first 5 rows of clean_df are:")
print(clean_df.head())
    #.head() = first 5 rows, otherwise the terminal gets too long

#Validation checks (6 in total) ############################################################################################################################################################

#1. Duplicate trades
print_validation_check("Duplicate trades", duplicate_trades)

#2. Missing owners
missing_owners = clean_df[clean_df["owner"].isna()]
    #.isna() = check whether values are missing
number_of_missing_owners = len(missing_owners)
print_validation_check("Missing owners", missing_owners)

#3. Missing settlement dates
missing_settlement_dates = clean_df[clean_df["settlement_date"].isna()]
number_of_missing_settlement_dates = len(missing_settlement_dates)
print_validation_check("Missing settlement dates", missing_settlement_dates)

#4. Failed trades
failed_trades = clean_df[clean_df["status"] == "Failed"]
number_of_failed_trades = len(failed_trades)
print_validation_check("Failed trades", failed_trades)

#5. Overdue trades
# "Overdue" only makes sense for a trade that's still IN FLIGHT - a trade that's
# already Settled isn't overdue just because time has passed, and a Failed trade
# is already covered by the Failed Trades check above, so it isn't double-counted here.
today = pd.Timestamp.today().normalize()
IN_FLIGHT_STATUSES = ["Executed", "Validated", "Pending Settlement"]

overdue_trades = clean_df[
    (clean_df["settlement_date"] < today) &   # < is an inequality
    (clean_df["status"].isin(IN_FLIGHT_STATUSES))
]
number_of_overdue_trades = len(overdue_trades)
print_validation_check("Overdue trades", overdue_trades)

#6. High priority failed trades
high_priority_trades = clean_df[clean_df["priority"] == "High"]
number_of_high_priority_trades = len(high_priority_trades)

high_priority_failed_trades = clean_df[
    (clean_df["priority"] == "High") &
    (clean_df["status"] == "Failed")
]
    #linebreak is useful for stacking multiple conditions
number_of_high_priority_failed_trades = len(high_priority_failed_trades)
print_validation_check("High priority failed trades", high_priority_failed_trades)

#Validation report ############################################################################################################################################################
validation_issues = []

for _, row in missing_owners.iterrows():
    validation_issues.append({
        "trade_id": row["trade_id"], "issue": "Missing Owner", "severity": "Medium",
        "reason": "No individual has been assigned responsibility for investigating or resolving the trade.",
    })

for _, row in missing_settlement_dates.iterrows():
    validation_issues.append({
        "trade_id": row["trade_id"], "issue": "Missing Settlement Date", "severity": "High",
        "reason": "The system cannot determine when the trade is due to settle.",
    })

for _, row in duplicate_trades.iterrows():
    validation_issues.append({
        "trade_id": row["trade_id"], "issue": "Duplicate Trade ID", "severity": "High",
        "reason": "Duplicate records may result in incorrect reporting or processing.",
    })

for _, row in failed_trades.iterrows():
    validation_issues.append({
        "trade_id": row["trade_id"], "issue": "Failed Trade", "severity": "High",
        "reason": "The trade has not completed successfully and requires investigation.",
    })

for _, row in overdue_trades.iterrows():
    validation_issues.append({
        "trade_id": row["trade_id"], "issue": "Overdue Trade", "severity": "High",
        "reason": "The settlement date has passed and the trade remains unresolved.",
    })

for _, row in high_priority_failed_trades.iterrows():
    validation_issues.append({
        "trade_id": row["trade_id"], "issue": "High Priority Failed Trade", "severity": "Critical",
        "reason": "A high-priority trade has failed and requires immediate attention.",
    })

validation_report_df = pd.DataFrame(validation_issues)

print("\nVALIDATION REPORT \nNumber of issues:", len(validation_report_df))
print(validation_report_df)

validation_report_df.to_csv("Reports/CSV/validation_report.csv", index=False)
print("\nValidation report exported successfully.")

#Count-based KPIs ############################################################################################################################################################
clean_total_trades = raw_total_trades - number_of_duplicate_trades

settled_trades_count = len(clean_df[clean_df["status"] == "Settled"])

completion_rate = (settled_trades_count / clean_total_trades) * 100
failure_rate = (number_of_failed_trades / clean_total_trades) * 100
overdue_rate = (number_of_overdue_trades / clean_total_trades) * 100

if number_of_high_priority_trades > 0:
    high_priority_failure_rate = (
        number_of_high_priority_failed_trades / number_of_high_priority_trades
    ) * 100
else:
    high_priority_failure_rate = 0

kpi_summary_df = pd.DataFrame([
    {"KPI": "Completion Rate", "Value": round(completion_rate, 2)},
    {"KPI": "Failure Rate", "Value": round(failure_rate, 2)},
    {"KPI": "Overdue Rate", "Value": round(overdue_rate, 2)},
    {"KPI": "High Priority Failure Rate", "Value": round(high_priority_failure_rate, 2)},
])

print("\nKPI DATAFRAME")
print(kpi_summary_df)

kpi_summary_df.to_csv("Reports/CSV/kpi_summary.csv", index=False)

#Value-based exposure measures (4 in total) ############################################################################################################################################################
# Count-based KPIs above answer "how many trades have an issue?". These exposure
# measures answer the question a risk manager actually cares about: "how much MONEY
# is at stake?" - a handful of failed trades matters a lot more if they're worth
# $50m combined than if they're worth $5k combined.
OUTSTANDING_STATUSES = ["Executed", "Validated", "Pending Settlement"]
    # notional still "live" in the pipeline, i.e. not yet Settled or Failed

total_notional = clean_df["notional"].sum()
outstanding_notional = clean_df[clean_df["status"].isin(OUTSTANDING_STATUSES)]["notional"].sum()
failed_notional = failed_trades["notional"].sum()
overdue_notional = overdue_trades["notional"].sum()

exposure_summary_df = pd.DataFrame([
    {"Exposure Measure": "Total Notional", "Value": round(total_notional, 2)},
    {"Exposure Measure": "Outstanding Notional", "Value": round(outstanding_notional, 2)},
    {"Exposure Measure": "Failed Notional", "Value": round(failed_notional, 2)},
    {"Exposure Measure": "Overdue Notional", "Value": round(overdue_notional, 2)},
])

print("\nEXPOSURE SUMMARY (value-based, not count-based)")
print(exposure_summary_df)

exposure_summary_df.to_csv("Reports/CSV/exposure_summary.csv", index=False)

#Average time-to-settlement ############################################################################################################################################################
# lifecycle_df has one row per (trade_id, stage) the trade actually reached, with a
# real timestamp for each. To measure time-to-settlement we need, for every trade
# that made it all the way to Settled, the gap between its "Executed" timestamp and
# its "Settled" timestamp.
executed_times = lifecycle_df[lifecycle_df["stage"] == "Executed"].set_index("trade_id")["timestamp"]
settled_times = lifecycle_df[lifecycle_df["stage"] == "Settled"].set_index("trade_id")["timestamp"]

settlement_durations = (settled_times - executed_times).dropna()
    # subtracting two datetime Series (matched by trade_id index) gives a Series of Timedeltas
    # .dropna() removes any trade_id that's in one Series but not the other

if len(settlement_durations) > 0:
    average_settlement_hours = settlement_durations.mean().total_seconds() / 3600
else:
    average_settlement_hours = 0

print(f"\nAverage time-to-settlement: {round(average_settlement_hours, 1)} hours "
      f"(based on {len(settlement_durations)} settled trades)")

settlement_summary_df = pd.DataFrame([{
    "Metric": "Average Time-to-Settlement (hours)",
    "Value": round(average_settlement_hours, 1),
    "Trades Measured": len(settlement_durations),
}])

settlement_summary_df.to_csv("Reports/CSV/settlement_summary.csv", index=False)

#Exporting clean trades ############################################################################################################################################################
clean_df.to_csv("Reports/CSV/clean_trades.csv", index=False)
print("\nClean trades exported successfully.")

print("\nSUMMARY")
print("Raw total trades:", raw_total_trades)
print("Clean total trades:", clean_total_trades)
print("Number of duplicate trades:", number_of_duplicate_trades)
print("Number of missing owners:", number_of_missing_owners)
print("Number of missing settlement dates:", number_of_missing_settlement_dates)
print("Number of overdue trades:", number_of_overdue_trades)
print("Number of failed trades:", number_of_failed_trades)
print("Number of high priority trades:", number_of_high_priority_trades)
print("Number of high priority failed trades:", number_of_high_priority_failed_trades)
print("Completion rate:", round(completion_rate, 2), "%")
print("Failure rate:", round(failure_rate, 2), "%")
print("Overdue rate:", round(overdue_rate, 2), "%")
print("High priority failure rate:", round(high_priority_failure_rate, 2), "%")
print("Total notional:", round(total_notional, 2))
print("Outstanding notional:", round(outstanding_notional, 2))
print("Failed notional:", round(failed_notional, 2))
print("Overdue notional:", round(overdue_notional, 2))

#Exposure concentration (which client / asset class is carrying the most risk) ############################################################################################################################################################
# Two trades of equal COUNT can matter very differently depending on whose book
# they sit in - this is what lets the AI summary comment on WHERE the exposure is
# concentrated, not just how much of it there is in total.
notional_by_client = clean_df.groupby("client_name")["notional"].sum().sort_values(ascending=False)
notional_by_asset_class = clean_df.groupby("asset_class")["notional"].sum().sort_values(ascending=False)

top_client_name = notional_by_client.index[0]
top_client_notional = notional_by_client.iloc[0]
top_client_share_of_total = (top_client_notional / total_notional) * 100 if total_notional > 0 else 0

top_asset_class_name = notional_by_asset_class.index[0]
top_asset_class_notional = notional_by_asset_class.iloc[0]
top_asset_class_share_of_total = (
    (top_asset_class_notional / total_notional) * 100 if total_notional > 0 else 0
)

print(f"\nTop client by exposure: {top_client_name} "
      f"({round(top_client_notional, 2)}, {round(top_client_share_of_total, 1)}% of total notional)")
print(f"Top asset class by exposure: {top_asset_class_name} "
      f"({round(top_asset_class_notional, 2)}, {round(top_asset_class_share_of_total, 1)}% of total notional)")

#AI operational summary ############################################################################################################################################################
# The three themes below (trade outcomes / operational risks / exposure
# concentrations) are deliberately the same three the CV bullet describes, so the
# AI summary this actually produces backs up that line if I'm asked to run it live.
prompt = f"""
You are a post-trade operations analyst.

Analyse the following metrics and write a concise operational summary.

Trade outcomes:
Clean trades reviewed: {clean_total_trades}
Settled trades: {settled_trades_count}
Failed trades: {number_of_failed_trades}
Still in progress (Executed / Validated / Pending Settlement): {clean_total_trades - settled_trades_count - number_of_failed_trades}
Completion rate: {round(completion_rate, 2)}%
Failure rate: {round(failure_rate, 2)}%
Average time-to-settlement: {round(average_settlement_hours, 1)} hours

Operational risk flags:
Overdue trades: {number_of_overdue_trades}
High-priority failed trades: {number_of_high_priority_failed_trades}
Missing owners: {number_of_missing_owners}

Exposure (value-based):
Total notional: {round(total_notional, 2)}
Outstanding notional: {round(outstanding_notional, 2)}
Failed notional: {round(failed_notional, 2)}
Overdue notional: {round(overdue_notional, 2)}

Exposure concentration:
Largest client exposure: {top_client_name}, {round(top_client_notional, 2)} ({round(top_client_share_of_total, 1)}% of total notional)
Largest asset class exposure: {top_asset_class_name}, {round(top_asset_class_notional, 2)} ({round(top_asset_class_share_of_total, 1)}% of total notional)

Write the summary in four short sections:
1. Trade outcomes - how the book performed overall
2. Operational risks - what needs attention and why
3. Notable exposure concentrations - where the value-based risk is concentrated, and whether that concentration is a concern
4. Recommended actions

Use concise, professional business language throughout.
"""

# Ollama needs a local server running (and the llama3.2 model pulled) to work. That
# won't always be true - e.g. this project might be marked/demoed on a machine
# without Ollama installed - so this is wrapped in a try/except rather than letting
# the whole script crash if the AI summary step isn't available.
if OLLAMA_AVAILABLE:
    try:
        response = chat(
            model="llama3.2",
            messages=[{"role": "user", "content": prompt}],
        )
        operational_summary = response.message.content
        print("\nOPERATIONAL SUMMARY (generated by Llama 3.2 via Ollama)")
        print(operational_summary)
    except Exception as ollama_error:
        print(f"\nCould not reach Ollama ({ollama_error}). Skipping AI summary generation.")
        operational_summary = (
            "AI operational summary unavailable: could not connect to a local Ollama "
            "server running Llama 3.2. Start Ollama and re-run this script to generate one.\n\n"
            f"Raw metrics for reference:\n{prompt}"
        )
else:
    print("\n'ollama' package not installed - skipping AI summary generation.")
    operational_summary = (
        "AI operational summary unavailable: the 'ollama' Python package is not installed.\n\n"
        f"Raw metrics for reference:\n{prompt}"
    )

with open("Reports/operational_summary.txt", "w") as file:
    file.write(operational_summary)

print("\nOperational summary exported successfully.")

#Excel exports ############################################################################################################################################################
clean_df.to_excel("Reports/Excel/clean_trades.xlsx", index=False)
validation_report_df.to_excel("Reports/Excel/validation_report.xlsx", index=False)
kpi_summary_df.to_excel("Reports/Excel/kpi_summary.xlsx", index=False)
exposure_summary_df.to_excel("Reports/Excel/exposure_summary.xlsx", index=False)
settlement_summary_df.to_excel("Reports/Excel/settlement_summary.xlsx", index=False)

print("\nAll reports exported successfully (CSV + Excel).")
